import Head from 'next/head'
import { FC } from 'react'

interface PageTitleProps {
    title: string
}

export default function PageTitle(props: PageTitleProps) {
    const pageTitle: string = `${capitalizeFirstLetter(props.title)} | Slackbear`
    return (
        <Head>
            <title>{pageTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

function capitalizeFirstLetter(str: string) {
    const sentance: string = removeHypen(str)
    const words = sentance.split(" ")

    for (let i = 0; i < words.length; i++) {
        words[i] = words[i][0].toUpperCase() + words[i].substr(1);
    }

    return words.join(" ")
}

function removeHypen(str: string) {
    return str.replace('-', ' ')
}